#!/usr/bin/env bash
set -euo pipefail
if [[ "${1:-}" =~ ^(build|test|run|coverage|cquery|aquery)$ ]] && ! [[ "$*" =~ (--config=|-c[[:space:]]|--compilation_mode=) ]]; then
  set -- "$1" --config=dbg "${@:2}"
fi
exec "${BAZEL_REAL}" "$@"
